# Use official Node.js runtime as a base image
FROM node:16

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the remaining source code to the container
COPY . .

# Expose the port your app runs on
EXPOSE 4000

# Start the app
CMD ["npm", "run", "dev"]
